stages:
  - mirror
  - test

github_mirror:
  stage: mirror
  script:
    - git push --mirror -f git@github.com:namboy94/html-index-generator.git

test_generating_index_for_coverage:
  stage: test
  script:
    - python html-generator.py /var/www/coverage.namibsun.net/public_html
      /var/www/coverage.namibsun.net/public_html/index.html
      -t template.html

test_generating_index_for_gitstats:
  stage: test
  script:
    - python html-generator.py /var/www/gitstats.namibsun.net/public_html
      /var/www/gitstats.namibsun.net/public_html/index.html
      -t template.html

test_generating_index_for_documentation:
  stage: test
  script:
    - python html-generator.py /var/www/docs.namibsun.net/public_html
      /var/www/docs.namibsun.net/public_html/index.html
      -t template.html -n Documentation

stylecheck:
  stage: test
  script:
    - pep8 .